"""Claude-assisted patent classification suggestions.

Claude proposes candidate CPC and USPC classifications based on the
user-approved search concepts. The suggestions are reviewed by the
user before they are used for classification refinement.

Classification definitions are intentionally NOT generated by Claude.
"""

from __future__ import annotations

import json
import re
from typing import Any

from models.claude_client import ClaudeClient


SYSTEM_PROMPT = """
You are an expert patent classification analyst.

Given a set of user-approved patent search concepts and their keywords,
identify relevant candidate CPC and USPC classifications.

Your role is to suggest classifications for human review.

Do NOT:
- apply or select classifications on behalf of the user
- generate patent search expressions
- generate CPC or USPC definitions
- invent classification codes
- use IPC classifications
- return unrelated classifications

Return ONLY valid JSON.
"""


USER_TEMPLATE = """
The user has approved the following patent search concepts:

{concepts}

Identify relevant candidate CPC and USPC classifications.

Return exactly this JSON structure:

{{
  "cpc": [
    {{
      "classification": "G06V 20/588",
      "concept": "Lane Detection Core Function",
      "reason": "Brief explanation of why this classification is relevant."
    }}
  ],
  "uspc": [
    {{
      "class": "701",
      "subclass": "",
      "concept": "Autonomous Vehicle Navigation",
      "reason": "Brief explanation of why this classification is relevant."
    }}
  ]
}}

Rules:

- Suggest up to 10 CPC candidates.
- Suggest up to 10 USPC candidates.
- Only suggest classifications that are plausibly relevant to the
  technical concepts provided.
- Prefer specific classifications over extremely broad classifications.
- CPC must use a valid-looking CPC format such as "G06V 20/588".
- USPC class must be numeric.
- USPC subclass should be provided when it can be identified reliably;
  otherwise use an empty string.
- Do not fabricate definitions.
- Do not include classifications merely because they are common in
  the technology area.
- The user will review all suggestions before they are used.
- Return JSON only.
"""


def _clean_text(value: Any) -> str:
    return str(value or "").strip()


def _extract_json(raw: str) -> dict[str, Any]:
    text = _clean_text(raw)

    if not text:
        raise ValueError("Claude returned an empty classification response.")

    text = re.sub(
        r"^```(?:json)?\s*",
        "",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(r"\s*```$", "", text)

    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Claude returned invalid classification JSON: {exc}"
        ) from exc

    if not isinstance(payload, dict):
        raise ValueError("Claude classification response must be a JSON object.")

    return payload


def _normalize_cpc(raw: Any) -> list[dict[str, str]]:
    if not isinstance(raw, list):
        return []

    results = []

    for item in raw:
        if not isinstance(item, dict):
            continue

        classification = _clean_text(item.get("classification"))
        concept = _clean_text(item.get("concept"))
        reason = _clean_text(item.get("reason"))

        if not classification:
            continue

        results.append(
            {
                "classification": classification,
                "concept": concept,
                "reason": reason,
            }
        )

    return results[:10]


def _normalize_uspc(raw: Any) -> list[dict[str, str]]:
    if not isinstance(raw, list):
        return []

    results = []

    for item in raw:
        if not isinstance(item, dict):
            continue

        uspc_class = _clean_text(item.get("class"))
        subclass = _clean_text(item.get("subclass"))
        concept = _clean_text(item.get("concept"))
        reason = _clean_text(item.get("reason"))

        if not uspc_class:
            continue

        results.append(
            {
                "class": uspc_class,
                "subclass": subclass,
                "concept": concept,
                "reason": reason,
            }
        )

    return results[:10]


def generate_classification_suggestions(
    concepts: list[dict[str, Any]],
    client: ClaudeClient,
) -> dict[str, list[dict[str, str]]]:
    """Generate CPC and USPC classification candidates from approved concepts."""

    if not concepts:
        raise ValueError(
            "At least one approved search concept is required."
        )

    concept_text = json.dumps(
        concepts,
        ensure_ascii=False,
        indent=2,
    )

    prompt = USER_TEMPLATE.format(
        concepts=concept_text,
    )

    raw = client.complete(
        system=SYSTEM_PROMPT,
        user=prompt,
        max_tokens=1800,
    )

    payload = _extract_json(raw)

    cpc = _normalize_cpc(payload.get("cpc"))
    uspc = _normalize_uspc(payload.get("uspc"))

    if not cpc and not uspc:
        raise ValueError(
            "Claude returned no valid CPC or USPC classification suggestions."
        )

    return {
        "cpc": cpc,
        "uspc": uspc,
    }
