"""
Patent deduplication service.

Deduplicates patents at two levels:

1. Exact publication/application record
2. USPTO continuity family

The second level prevents continuation/divisional-related publications
from occupying multiple slots in the embedding and ranking pipeline.

The original PatentRecord objects are not modified.
"""

from __future__ import annotations

import sys
from pathlib import Path
from collections import defaultdict

# Ensure the project root is importable regardless of launch directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from models.schemas import PatentRecord  # noqa: E402
from utils.logger import get_logger  # noqa: E402

log = get_logger(__name__)


def _normalise_identifier(value: str | None) -> str:
    """Normalise an identifier for reliable comparison."""

    if not value:
        return ""

    return "".join(
        str(value).strip().upper().split()
    )


def _publication_key(patent: PatentRecord) -> str:
    """
    Return the strongest available exact-record identifier.

    patent_id is currently the publication identifier generated by the
    USPTO service, falling back to the raw patent_id if necessary.
    """

    return _normalise_identifier(patent.patent_id)


def _family_key(patent: PatentRecord) -> str:
    """
    Return the USPTO continuity-family key.

    If continuity_family_id is unavailable, fall back to the individual
    publication so that unrelated patents are never accidentally grouped.
    """

    family_id = _normalise_identifier(
        patent.continuity_family_id
    )

    if family_id:
        return f"FAMILY:{family_id}"

    return f"PATENT:{_publication_key(patent)}"


def _representative_score(
    patent: PatentRecord,
) -> tuple[int, str, str]:
    """Prefer patents with an abstract, then the earliest date, then stable ID."""

    return (
        int(bool((patent.patent_abstract or "").strip())),
        patent.patent_date or "9999-99-99",
        patent.patent_id,
    )


def _choose_representative(
    members: list[PatentRecord],
) -> PatentRecord:
    """Select a representative where abstracted records and earlier dates win."""

    return sorted(
        members,
        key=lambda patent: (
            -_representative_score(patent)[0],
            _representative_score(patent)[1],
            _representative_score(patent)[2],
        ),
    )[0]


def deduplicate(
    patents: list[PatentRecord],
) -> list[PatentRecord]:
    """
    Remove exact duplicates and collapse USPTO continuity families.

    Parameters
    ----------
    patents:
        Patent records returned by the search stage.

    Returns
    -------
    list[PatentRecord]
        One representative patent per continuity family.
    """

    if not patents:
        log.info(
            "Deduplication complete",
            extra={
                "input": 0,
                "exact_unique": 0,
                "families": 0,
                "final_unique": 0,
            },
        )
        return []

    # ---------------------------------------------------------------
    # Stage 1
    # Exact publication deduplication
    # ---------------------------------------------------------------

    publications: dict[str, PatentRecord] = {}

    for patent in patents:

        key = _publication_key(patent)

        if not key:
            log.warning(
                "Patent has empty publication identifier",
                extra={
                    "patent_id": patent.patent_id,
                },
            )
            continue

        if key not in publications:
            publications[key] = patent
        else:
            log.debug(
                "Exact publication duplicate removed",
                extra={
                    "patent_id": patent.patent_id,
                },
            )

    exact_unique = list(publications.values())

    # ---------------------------------------------------------------
    # Stage 2
    # USPTO continuity-family grouping
    # ---------------------------------------------------------------

    families: dict[str, list[PatentRecord]] = defaultdict(list)

    for patent in exact_unique:

        key = _family_key(patent)

        families[key].append(patent)

    representatives: list[PatentRecord] = []

    family_members_removed = 0

    for family_key, members in families.items():

        representative = _choose_representative(members)

        representatives.append(representative)

        removed = len(members) - 1

        family_members_removed += removed

        if removed > 0:

            log.info(
                "Patent continuity family collapsed",
                extra={
                    "family_id": family_key,
                    "representative": representative.patent_id,
                    "members": [
                        patent.patent_id
                        for patent in members
                    ],
                    "members_removed": removed,
                },
            )

    # ---------------------------------------------------------------
    # Summary
    # ---------------------------------------------------------------

    log.info(
        "Family-aware deduplication complete",
        extra={
            "input": len(patents),
            "exact_unique": len(exact_unique),
            "families": len(families),
            "family_members_removed": family_members_removed,
            "final_unique": len(representatives),
        },
    )

    return representatives